##
#
# Travis CI script for keyvi-server
#

language: cpp

compiler:
  - gcc

python:
  - 3.5

sudo: required

services:
  - docker

env:
  matrix:
    - BUILD_TYPE=linux      DOCKER_IMAGE=keyvidev/ubuntu-builder      CONF=release
    - BUILD_TYPE=linux      DOCKER_IMAGE=keyvidev/ubuntu-builder      CONF=debug

    - BUILD_TYPE=python     DOCKER_IMAGE=keyvidev/ubuntu-builder      PYTHON_VERSION=3.5.7
    - BUILD_TYPE=python     DOCKER_IMAGE=keyvidev/ubuntu-builder      PYTHON_VERSION=3.6.9
    - BUILD_TYPE=python     DOCKER_IMAGE=keyvidev/ubuntu-builder      PYTHON_VERSION=3.7.4
    - BUILD_TYPE=python     DOCKER_IMAGE=keyvidev/ubuntu-builder      PYTHON_VERSION=3.8.0
    - BUILD_TYPE=python     DOCKER_IMAGE=keyvidev/ubuntu-builder      PYTHON_VERSION=pypy2.7-7.2.0

    - BUILD_TYPE=sdist      DOCKER_IMAGE=keyvidev/ubuntu-builder

    - BUILD_TYPE=manylinux  DOCKER_IMAGE=keyvidev/manylinux-builder         PYTHON_PATH=cp35-cp35m
    #- BUILD_TYPE=manylinux  DOCKER_IMAGE=keyvidev/manylinux-builder         PYTHON_PATH=cp36-cp36m
    #- BUILD_TYPE=manylinux  DOCKER_IMAGE=keyvidev/manylinux-builder         PYTHON_PATH=cp37-cp37m
    #- BUILD_TYPE=manylinux  DOCKER_IMAGE=keyvidev/manylinux-builder         PYTHON_PATH=cp38-cp38

    - BUILD_TYPE=style      DOCKER_IMAGE=keyvidev/ubuntu-builder

  global:
    - GITHUB_REPO='KeyviDev/keyvi-server'

matrix:
  include:
    - os: osx
      osx_image: xcode7.3
      compiler: clang
      env: BUILD_TYPE=osx PYTHON_VERSION=3.5.7
    - os: osx
      osx_image: xcode9.4
      compiler: clang
      env: BUILD_TYPE=osx PYTHON_VERSION=3.6.9
    - os: osx
      osx_image: xcode9.4
      compiler: clang
      env: BUILD_TYPE=osx PYTHON_VERSION=3.7.4
    - os: osx
      osx_image: xcode9.4
      compiler: clang
      env: BUILD_TYPE=osx PYTHON_VERSION=3.8.0
    - os: osx
      osx_image: xcode9.4
      compiler: clang
      env: BUILD_TYPE=osx PYTHON_VERSION=pypy2.7-6.0.0

before_install:
  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then source ./travis/setup_osx.sh ; fi

install:
  - if [ "$DOCKER_IMAGE" != "" ]; then docker pull $DOCKER_IMAGE ; fi

script:
  - if [ "$BUILD_TYPE" == "linux" ]; then docker run --rm -v `pwd`:/io -e CONF $DOCKER_IMAGE  /io/travis/build_linux.sh ; fi

  - if [ "$BUILD_TYPE" == "python" ]; then
      docker run --rm -v `pwd`:/io -e CONF -e PYTHON_VERSION $DOCKER_IMAGE  /io/travis/build_python.sh ; fi

  - if [ "$BUILD_TYPE" == "manylinux" ]; then
      docker run --rm -v `pwd`:/io -e PYTHON_PATH $DOCKER_IMAGE  /io/travis/build_manylinux_wheels.sh ; fi

  - if [ "$BUILD_TYPE" == "sdist" ]; then
      docker run --rm -v `pwd`:/io -e PYTHON_VERSION $DOCKER_IMAGE  /io/travis/build_sdist_package.sh ; fi

  - if [ "$BUILD_TYPE" == "osx" ]; then source ./travis/build_osx_package.sh ; fi

  - if [ "$BUILD_TYPE" == "coverage" ]; then
      docker run --rm -v `pwd`:/io -e TRAVIS -e TRAVIS_JOB_ID -e TRAVIS_BRANCH -e TRAVIS_PULL_REQUEST $DOCKER_IMAGE /io/travis/coverage.sh ; fi

  - if [ "$BUILD_TYPE" == "style" ] && [ "$TRAVIS_PULL_REQUEST" != "false" ]; then
      docker run --rm -v `pwd`:/io -e TRAVIS_COMMIT_RANGE $DOCKER_IMAGE /io/travis/style.sh ; fi

deploy:
  provider: script
  script: travis/upload_packages.sh
  skip_cleanup: true
  on:
    tags: true
