# Build on Linux

name: Build on Linux

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    name: ${{matrix.buildname}}
    strategy:
      fail-fast: false
      matrix:
        include:
          - buildname: 'linux / release'
            type: Release
          - buildname: 'linux / debug'
            type: Debug  
    steps:
      - name: install deps
        run: |
          sudo apt-get update
          sudo apt-get install -y libsnappy-dev libzzip-dev zlib1g-dev
          sudo apt-get install -y libssl-dev libgflags-dev libleveldb-dev libgoogle-perftools-dev         
      - name: Cache Boost
        id: cache-boost
        uses: actions/cache@v1
        with:
          path: boost_1_72_0/install
          key: ${{ runner.os }}-boost_1_72_0-keyviserver
      - name: Install Boost
        if: steps.cache-boost.outputs.cache-hit != 'true'
        run: |
          wget https://dl.bintray.com/boostorg/release/1.72.0/source/boost_1_72_0.tar.gz
          tar -zxf boost_1_72_0.tar.gz
          cd boost_1_72_0
          mkdir -p install
          ./bootstrap.sh --without-libraries=graph_parallel,python
          ./b2 -d0 --prefix=./install install
      - name: Cache protobuf
        id: cache-protobuf
        uses: actions/cache@v1
        env:
          PROTO_MAJOR: 3 
          PROTO_MINOR: 11 
          PROTO_PATCH: 4
        with:
          path: protobuf-${{ env.PROTO_MAJOR }}.${{ env.PROTO_MINOR }}.${{ env.PROTO_PATCH }}/install
          key: ${{ runner.os }}-protobuf-${{ env.PROTO_MAJOR }}-${{ env.PROTO_MINOR }}-${{ env.PROTO_PATCH }}-keyviserver
      - name: Install Protobuf
        if: steps.cache-protobuf.outputs.cache-hit != 'true'
        run: |
          wget https://github.com/google/protobuf/releases/download/v$PROTO_MAJOR.$PROTO_MINOR.$PROTO_PATCH/protobuf-cpp-$PROTO_MAJOR.$PROTO_MINOR.$PROTO_PATCH.tar.gz
          tar -zxvf protobuf-cpp-$PROTO_MAJOR.$PROTO_MINOR.$PROTO_PATCH.tar.gz
          cd protobuf-$PROTO_MAJOR.$PROTO_MINOR.$PROTO_PATCH
          ./configure --prefix=./install
          make
          make install
          
#          
#      - name: checkout from git
#        uses: actions/checkout@v2
 #     
 #     - name: build with cmake
 #       uses: lukka/run-cmake@v3
 #       with:
 #         cmakeListsOrSettingsJson: CMakeListsTxtAdvanced
 #         cmakeListsTxtPath: '${{ github.workspace }}/CMakeLists.txt'
 #         cmakeBuildType: ${{matrix.buildname}}
 #         cmakeAppendedArgs: '-DBOOST_ROOT=${{ github.workspace }}/boost_1_72_0/install -DPROTOBUF_PATH=${{ github.workspace }}/protobuf-3.11.4/install  -DBoost_DEBUG=ON'
 #         buildWithCMake: true
