# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    runs-on: ubuntu-latest
    name: ${{matrix.buildname}}
    strategy:
      fail-fast: false
      matrix:
        include:
          - buildname: 'linux / release'
            type: Release
          - buildname: 'linux / debug'
            type: Debug
    container:
      image: keyvidev/ubuntu-builder
    steps:
      - name: checkout from git
        uses: actions/checkout@v2
      
      - name: build with cmake
        uses: lukka/run-cmake@v3
        with:
          cmakeListsOrSettingsJson: CMakeListsTxtAdvanced
          cmakeListsTxtPath: '${{ github.workspace }}/CMakeLists.txt'
          cmakeBuildType: ${{matrix.buildname}}   
          buildWithCMake: true
