# This is a basic workflow to help you get started with Actions

name: Build on Mac

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest
    name: ${{matrix.buildname}}
    strategy:
      fail-fast: false
      matrix:
        include:
          - buildname: 'mac / python 3.9'
            python: 3.9.0
          - buildname: 'mac / python 3.8'
            python: 3.8.6
            
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Install dependencies from brew
        run: |
          brew update
          brew install zlib
          brew install snappy
          brew install openssl gnu-getopt coreutils
          brew install gflags protobuf leveldb
          brew install gperftools
      - name: Cache Boost
        id: cache-boost
        uses: actions/cache@v1
        with:
          path: boost_1_72_0/installdir
          key: ${{ runner.os }}-boost_1_72_0-fs-system-test
      - name: Install Boost
        if: steps.cache-boost.outputs.cache-hit != 'true'
        run: |
          wget https://dl.bintray.com/boostorg/release/1.72.0/source/boost_1_72_0.tar.gz
          tar -zxf boost_1_72_0.tar.gz
          cd boost_1_72_0
          mkdir -p installdir
          ./bootstrap.sh --prefix=./installdir --with-libraries=filesystem,system,test,program_options,iostreams,regex,thread,date_time,atomic
          ./b2 install
      - name: checkout from git
        uses: actions/checkout@v2
      
      - name: build with cmake
        uses: lukka/run-cmake@v3
        with:
          cmakeListsOrSettingsJson: CMakeListsTxtAdvanced
          cmakeListsTxtPath: '${{ github.workspace }}/CMakeLists.txt'
          cmakeBuildType: ${{matrix.buildname}}   
          cmakeAppendedArgs: '-DBOOST_ROOT=${{ github.workspace }}/boost_1_72_0/installdir -DBoost_DEBUG=ON'
          buildWithCMake: true
