# Build python bindings
name: Build python bindings

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{matrix.os}}
    strategy:
      fail-fast: false
      matrix:
        python-version: [ '3.6', '3.7', '3.8', '3.9' ]
        os: [ 'macos-latest', 'ubuntu-latest' ]
    name: Python ${{ matrix.python-version }} on ${{ matrix.os }} build
    env:
      PROTO_MAJOR: 3 
      PROTO_MINOR: 11 
      PROTO_PATCH: 4
    steps:
      - name: install Linux deps
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update
          sudo apt-get install -y libsnappy-dev libzzip-dev zlib1g-dev libboost-all-dev
          sudo apt-get install -y libssl-dev libgflags-dev libleveldb-dev libgoogle-perftools-dev
          sudo apt-get install ccache
      - name: install macOS deps
        if: runner.os == 'macOS'
        run: |
          brew update
          brew install zlib snappy openssl gnu-getopt coreutils gflags leveldb gperftools boost
          brew install ccache
      - name: checkout from git
        uses: actions/checkout@v2
      
      # Ccache https://cristianadam.eu/20200113/speeding-up-c-plus-plus-github-actions-using-ccache/
    
      - name: Prepare ccache timestamp
        id: ccache_cache_timestamp
        shell: cmake -P {0}
        run: |
          string(TIMESTAMP current_date "%Y-%m-%d-%H;%M;%S" UTC)
          message("::set-output name=timestamp::${current_date}")
      - name: ccache cache files
        uses: actions/cache@v2
        with:
          path: .ccache
          key: ${{ matrix.os }}-Release-ccache-${{ steps.ccache_cache_timestamp.outputs.timestamp }}
          restore-keys: |
            ${{ matrix.os }}-Release-ccache-
      - name: Configure ccache
        id: ccache_configure
        run: |
          ccache --set-config=cache_dir=$GITHUB_WORKSPACE/.ccache
          ccache --set-config=max_size=500M
          ccache --set-config=compression=true
          ccache -p
          ccache -z
      
      - name: Cache protobuf
        id: cache_protobuf
        uses: actions/cache@v2
        with:
          path: protobuf-${{ env.PROTO_MAJOR }}.${{ env.PROTO_MINOR }}.${{ env.PROTO_PATCH }}/installdir
          key: ${{ runner.os }}-protobuf-${{ env.PROTO_MAJOR }}-${{ env.PROTO_MINOR }}-${{ env.PROTO_PATCH }}-keyvi
      - name: Install Protobuf
        if: steps.cache_protobuf.outputs.cache-hit != 'true'
        run: |
          wget https://github.com/google/protobuf/releases/download/v$PROTO_MAJOR.$PROTO_MINOR.$PROTO_PATCH/protobuf-cpp-$PROTO_MAJOR.$PROTO_MINOR.$PROTO_PATCH.tar.gz
          tar -zxvf protobuf-cpp-$PROTO_MAJOR.$PROTO_MINOR.$PROTO_PATCH.tar.gz
          cd protobuf-$PROTO_MAJOR.$PROTO_MINOR.$PROTO_PATCH
          ./configure --prefix=$GITHUB_WORKSPACE/protobuf-$PROTO_MAJOR.$PROTO_MINOR.$PROTO_PATCH/installdir
          make
          make install
      - name: build with cmake
        uses: lukka/run-cmake@v3
        with:
          cmakeListsOrSettingsJson: CMakeListsTxtAdvanced
          cmakeListsTxtPath: '${{ github.workspace }}/CMakeLists.txt'
          cmakeBuildType: Release
          cmakeAppendedArgs: '-DCMAKE_PREFIX_PATH=${{ github.workspace }}/protobuf-$PROTO_MAJOR.$PROTO_MINOR.$PROTO_PATCH/installdir -D CMAKE_C_COMPILER_LAUNCHER=ccache -D CMAKE_CXX_COMPILER_LAUNCHER=ccache'
          buildWithCMake: true
          buildDirectory: '${{ github.workspace }}/build'
      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
          architecture: x64
      - run: |
          export PATH="/usr/lib/ccache:/usr/local/opt/ccache/libexec:$PATH"
          cd python
          python -m pip install -r requirements.txt
          python -m pip install redis
          python setup.py build
          python setup.py install --user
          python -m pytest tests
      
      - name: Stats from ccache
        id: ccache_stats
        run: |
          ccache -s
