# Build python bindings on Linux
name: Build python Linux

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ '3.6', '3.7', '3.8' ]
    name: Python ${{ matrix.python-version }} build
    env:
      PROTO_MAJOR: 3 
      PROTO_MINOR: 11 
      PROTO_PATCH: 4
    steps:
      - name: install deps
        run: |
          sudo apt-get update
          sudo apt-get install -y libsnappy-dev libzzip-dev zlib1g-dev
          sudo apt-get install -y libssl-dev libgflags-dev libleveldb-dev libgoogle-perftools-dev         
      - name: checkout from git
        uses: actions/checkout@v2
      - name: Cache Boost
        id: cache_boost
        uses: actions/cache@v2
        with:
          path: boost_1_72_0/install
          key: ${{ runner.os }}-boost_1_72_0-keyvi
      - name: Install Boost
        if: steps.cache_boost.outputs.cache-hit != 'true'
        run: |
          wget https://dl.bintray.com/boostorg/release/1.72.0/source/boost_1_72_0.tar.gz
          tar -zxf boost_1_72_0.tar.gz
          cd boost_1_72_0
          mkdir -p $GITHUB_WORKSPACE/boost/install
          ./bootstrap.sh --without-libraries=graph_parallel,python
          ./b2 --prefix=$GITHUB_WORKSPACE/boost/install install
      - name: Cache protobuf
        id: cache_protobuf
        uses: actions/cache@v2
        with:
          path: protobuf-${{ env.PROTO_MAJOR }}.${{ env.PROTO_MINOR }}.${{ env.PROTO_PATCH }}/install
          key: ${{ runner.os }}-protobuf-${{ env.PROTO_MAJOR }}-${{ env.PROTO_MINOR }}-${{ env.PROTO_PATCH }}-keyvi
      - name: Install Protobuf
        if: steps.cache_protobuf.outputs.cache-hit != 'true'
        run: |
          wget https://github.com/google/protobuf/releases/download/v$PROTO_MAJOR.$PROTO_MINOR.$PROTO_PATCH/protobuf-cpp-$PROTO_MAJOR.$PROTO_MINOR.$PROTO_PATCH.tar.gz
          tar -zxvf protobuf-cpp-$PROTO_MAJOR.$PROTO_MINOR.$PROTO_PATCH.tar.gz
          cd protobuf-$PROTO_MAJOR.$PROTO_MINOR.$PROTO_PATCH
          ./configure --prefix=$GITHUB_WORKSPACE/protobuf-$PROTO_MAJOR.$PROTO_MINOR.$PROTO_PATCH/install
          make
          make install
      - name: build with cmake
        uses: lukka/run-cmake@v3
        with:
          cmakeListsOrSettingsJson: CMakeListsTxtAdvanced
          cmakeListsTxtPath: '${{ github.workspace }}/CMakeLists.txt'
          cmakeBuildType: Release
          cmakeAppendedArgs: '-DBOOST_ROOT=${{ github.workspace }}/boost/install -DCMAKE_PREFIX_PATH=${{ github.workspace }}/protobuf-$PROTO_MAJOR.$PROTO_MINOR.$PROTO_PATCH/install'
          buildWithCMake: true
      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
          architecture: x64
      - run: |
          cd python
          python -m pip install -r requirements.txt
          python -m pip install redis
          python setup.py build
          python setup.py install --user
          python -m pytest tests
