# Build python bindings on Linux
name: Build python Linux

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ '3.6', '3.7', '3.8' ]
    name: Python ${{ matrix.python-version }} build
    steps:
      - uses: actions/checkout@v2
      - name: build with cmake
        uses: lukka/run-cmake@v3
        with:
          cmakeListsOrSettingsJson: CMakeListsTxtAdvanced
          cmakeListsTxtPath: '${{ github.workspace }}/CMakeLists.txt'
          cmakeBuildType: Release 
          buildWithCMake: true
          buildDirectory: '${{ github.workspace }}/build'
      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
          architecture: x64
      - run: |
          cd python
          python -m pip install -r requirements.txt
          python -m pip install redis
          python setup.py build
          python setup.py install --user
          python -m pytest tests
